_wandb:
    value:
        cli_version: 0.23.0
        e:
            kypj78xpazrfyued2d03jtbt57hf6f7w:
                args:
                    - --data-config
                    - configs/data.yaml
                    - --model-config
                    - configs/model.yaml
                codePath: src/training/train.py
                codePathLocal: src/training/train.py
                email: aldisa546@gmail.com
                executable: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
                git:
                    commit: eec6d0ddffe30e5e827a55ff94d9777338264bce
                    remote: https://github.com/aldisa546/quran-ayat-detector.git
                host: Syaamils-MacBook-Air.local
                os: macOS-15.1.1-arm64-arm-64bit
                program: /Users/syaamil/development/Quran-Bounding/quran-bounding-project/src/training/train.py
                python: CPython 3.9.6
                root: /Users/syaamil/development/Quran-Bounding/quran-bounding-project
                startedAt: "2025-11-23T23:21:10.477455Z"
                writerId: kypj78xpazrfyued2d03jtbt57hf6f7w
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
                - 80
            "2":
                - 1
                - 41
                - 80
            "3":
                - 13
                - 16
            "4": 3.9.6
            "5": 0.23.0
            "8":
                - 2
            "12": 0.23.0
            "13": darwin-arm64
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 32
box:
    value: 7.5
cache:
    value: false
cfg:
    value: null
classes:
    value: null
close_mosaic:
    value: 10
cls:
    value: 0.5
conf:
    value: null
copy_paste:
    value: 0
cos_lr:
    value: false
crop_fraction:
    value: 1
data:
    value: configs/data.yaml
degrees:
    value: 0
deterministic:
    value: true
device:
    value: cpu
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 120
erasing:
    value: 0.4
exist_ok:
    value: true
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: null
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.7
hsv_v:
    value: 0.4
imgsz:
    value: 640
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
label_smoothing:
    value: 0
line_width:
    value: null
lr0:
    value: 0.01
lrf:
    value: 0.01
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0
mode:
    value: train
model:
    value: yolov8s.pt
momentum:
    value: 0.937
mosaic:
    value: 1
multi_scale:
    value: false
name:
    value: yolo-ayat-detector
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 50
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: experiments
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: true
save_conf:
    value: false
save_crop:
    value: false
save_dir:
    value: experiments/yolo-ayat-detector
save_frames:
    value: false
save_hybrid:
    value: false
save_json:
    value: false
save_period:
    value: -1
save_txt:
    value: false
scale:
    value: 0.5
seed:
    value: 0
shear:
    value: 0
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: false
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: detect
time:
    value: null
tracker:
    value: botsort.yaml
translate:
    value: 0.1
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0.1
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 0
workspace:
    value: 4
