model:
  weights: "yolov8s.pt"
  pretrained: true
  task: "detect"
  batch: 32
  epochs: 100

logging:
  project: "experiments"
  name: "yolo-hafalan-detector"
  exist_ok: true
  save_period: 0
  verbose: true

