variants:
  non-tajwid: "https://storage.googleapis.com/gongaji-mushaf/mushaf/non-tajwid/image/webp"
  haji-umrah: "https://storage.googleapis.com/gongaji-mushaf/mushaf/haji-umrah/arabic/image/webp"
  mina-tajwid: "https://storage.googleapis.com/gongaji-mushaf/mushaf/mina-tajwid/image/webp"
  tikrar-tajwid-terjemah: "https://storage.googleapis.com/gongaji-mushaf/mushaf/tikrar-tajwid-terjemah/image/webp"
  quba: "https://storage.googleapis.com/gongaji-mushaf/mushaf/quba/image/webp"

